import { NavLink } from 'react-router-dom';
import { FiActivity, FiAward, FiBell, FiCheckCircle, FiClock, FiCreditCard, FiFileText, FiFlag, FiGrid, FiList, FiMapPin, FiMonitor, FiPlusCircle, FiShield, FiShuffle, FiTag, FiTrendingUp, FiUser, FiUserCheck, FiUsers, FiChevronLeft } from 'react-icons/fi';
import styles from './AdminSidebar.module.scss';

interface NavItem { label: string; path: string; icon: React.ReactNode; }
interface NavGroup { label: string; items: NavItem[]; }
const groups: NavGroup[] = [
  { label: 'TỔNG QUAN', items: [{ label: 'Tổng quan', path: '/admin', icon: <FiGrid size={18} /> }, { label: 'Trung tâm giải đấu', path: '/admin/tournament-hub', icon: <FiActivity size={18} /> }] },
  { label: 'CHUẨN BỊ GIẢI ĐẤU', items: [{ label: 'Quản lý giải đấu', path: '/admin/tournaments', icon: <FiList size={18} /> }, { label: 'Tạo và chỉnh sửa giải', path: '/admin/tournament-builder', icon: <FiPlusCircle size={18} /> }, { label: 'Quản lý trường đua', path: '/admin/venues', icon: <FiMapPin size={18} /> }, { label: 'Quản lý mã vé', path: '/admin/ticket-codes', icon: <FiTag size={18} /> }] },
  { label: 'XÉT DUYỆT VÀ NGƯỜI DÙNG', items: [{ label: 'Phê duyệt hồ sơ', path: '/admin/approval-center', icon: <FiShield size={18} /> }, { label: 'Quản lý người dùng', path: '/admin/users', icon: <FiUsers size={18} /> }] },
  { label: 'ĐIỀU HÀNH GIẢI ĐẤU', items: [{ label: 'Đối chiếu lệ phí', path: '/admin/entry-fees', icon: <FiCreditCard size={18} /> }, { label: 'Điều hành vòng đấu', path: '/admin/race-operations', icon: <FiFlag size={18} /> }, { label: 'Bốc thăm vị trí xuất phát', path: '/admin/post-position-draw', icon: <FiShuffle size={18} /> }, { label: 'Phân công trọng tài', path: '/admin/assign-officials', icon: <FiUserCheck size={18} /> }, { label: 'Danh sách cuộc đua', path: '/admin/race-list', icon: <FiCheckCircle size={18} /> }, { label: 'Theo dõi trực tiếp', path: '/admin/live-race', icon: <FiMonitor size={18} /> }] },
  { label: 'TỔNG KẾT', items: [{ label: 'Quỹ thưởng và giải thưởng', path: '/admin/purse-payouts', icon: <FiAward size={18} /> }, { label: 'Bảng xếp hạng', path: '/admin/leaderboard', icon: <FiTrendingUp size={18} /> }, { label: 'Báo cáo', path: '/admin/reports', icon: <FiFileText size={18} /> }, { label: 'Nhật ký hoạt động', path: '/admin/audit-log-viewer', icon: <FiClock size={18} /> }] },
];
const utilityItems: NavItem[] = [{ label: 'Thông báo', path: '/admin/notifications', icon: <FiBell size={18} /> }, { label: 'Tài khoản của tôi', path: '/admin/my-account', icon: <FiUser size={18} /> }];
interface AdminSidebarProps { collapsed?: boolean; onToggleCollapse?: () => void; }
const AdminSidebar = ({ collapsed = false, onToggleCollapse }: AdminSidebarProps) => <aside className={`${styles.sidebar} ${collapsed ? styles.collapsed : ''}`}><nav className={styles.nav}>{groups.map((group) => <section key={group.label} className={styles.group}>{!collapsed && <span className={styles.groupLabel}>{group.label}</span>}<div className={styles.navGroup}>{group.items.map((item) => <NavLink key={item.path} to={item.path} end={item.path === '/admin'} title={collapsed ? item.label : undefined} className={({ isActive }) => `${styles.navItem} ${isActive ? styles.navItemActive : ''}`}><span className={styles.navIcon}>{item.icon}</span>{!collapsed && <span className={styles.navLabel}>{item.label}</span>}</NavLink>)}</div></section>)}</nav><div className={styles.bottomBlock}><div className={styles.navGroup}>{utilityItems.map((item) => <NavLink key={item.path} to={item.path} title={collapsed ? item.label : undefined} className={({ isActive }) => `${styles.navItem} ${isActive ? styles.navItemActive : ''}`}><span className={styles.navIcon}>{item.icon}</span>{!collapsed && <span className={styles.navLabel}>{item.label}</span>}</NavLink>)}</div><button type="button" className={styles.collapseBtn} title={collapsed ? 'Mở rộng thanh điều hướng' : 'Thu gọn'} onClick={onToggleCollapse}><FiChevronLeft size={15} className={collapsed ? styles.flipped : ''} />{!collapsed && <span>Thu gọn</span>}</button></div></aside>;
export default AdminSidebar;
