import { useEffect, useMemo, useState } from 'react';
import { FiCheckCircle, FiChevronDown, FiEye, FiMapPin } from 'react-icons/fi';
import { declareRaceOfficial, getUnofficialRaces, type UnofficialRace } from '../../services/raceOperationService';
import { getTournaments, type TournamentResponse } from '../../services/tournamentService';
import { getRaceSchedule } from '../../services/schedulingService';
import { adminError, dateTime } from '../../utils/adminLabels';
import styles from './RaceList.module.scss';

type RaceRow = UnofficialRace & { entryCount: number; venueName?: string | null; venueCity?: string | null };
const RaceList = () => {
  const [tournaments, setTournaments] = useState<TournamentResponse[]>([]); const [tournamentId, setTournamentId] = useState<number | null>(null);
  const [races, setRaces] = useState<RaceRow[]>([]); const [selectedRaceId, setSelectedRaceId] = useState<number | null>(null); const [detail, setDetail] = useState<RaceRow | null>(null);
  const [loading, setLoading] = useState(true); const [declaring, setDeclaring] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const tournament = useMemo<TournamentResponse | null>(() => tournaments.find((item) => item.tournamentId === tournamentId) ?? null, [tournaments, tournamentId]);
  useEffect(() => { void getTournaments().then((items) => { setTournaments(items); setTournamentId(items[0]?.tournamentId ?? null); }).catch((err) => setError(adminError(err))).finally(() => setLoading(false)); }, []);
  const loadRaces = async (id: number) => { setLoading(true); setError(''); try { const list = await getUnofficialRaces(id); const schedules = await Promise.all(list.map(async (race) => { try { return await getRaceSchedule(race.raceId); } catch { return null; } })); const rows = list.map((race, index) => ({ ...race, entryCount: schedules[index]?.entries.length ?? 0, venueName: schedules[index]?.venueName, venueCity: schedules[index]?.venueCity })); setRaces(rows); setSelectedRaceId((current) => rows.some((race) => race.raceId === current) ? current : rows[0]?.raceId ?? null); } catch (err) { setError(adminError(err, 'Không tải được danh sách cuộc đua.')); setRaces([]); } finally { setLoading(false); } };
  useEffect(() => { if (tournamentId) void loadRaces(tournamentId); else setRaces([]); }, [tournamentId]);
  const selected = races.find((item) => item.raceId === selectedRaceId) ?? null;
  const declareOfficial = async (race: RaceRow) => { if (!window.confirm(`Chuyển cuộc đua #${race.raceNumber} sang trạng thái chính thức?`)) return; setDeclaring(true); setError(''); try { await declareRaceOfficial(race.raceId, { confirmedByAdmin: true }); setNotice(`Cuộc đua #${race.raceNumber} đã chuyển sang trạng thái chính thức.`); setDetail(null); if (tournamentId) await loadRaces(tournamentId); } catch (err) { setError(adminError(err, 'Không thể chuyển trạng thái cuộc đua.')); } finally { setDeclaring(false); } };
  return <div className={styles.page}><header><h1>Danh sách cuộc đua</h1><p>Theo dõi các cuộc đua chưa chính thức của giải đấu được chọn và chuyển trạng thái khi đủ điều kiện.</p></header>{notice && <div className={styles.notice}>{notice}</div>}{error && <div className={styles.error}>{error}</div>}
    <section className={styles.card}><div className={styles.filters}><label>Giải đấu<div><select value={tournamentId ?? ''} onChange={(event) => { setTournamentId(event.target.value ? Number(event.target.value) : null); setDetail(null); }}><option value="">-- Chọn giải đấu --</option>{tournaments.map((item) => <option key={item.tournamentId} value={item.tournamentId}>{item.name}</option>)}</select><FiChevronDown /></div></label><label>Cuộc đua hiện tại<div><select value={selectedRaceId ?? ''} onChange={(event) => setSelectedRaceId(event.target.value ? Number(event.target.value) : null)} disabled={races.length === 0}><option value="">-- Không có cuộc đua chưa chính thức --</option>{races.map((race) => <option key={race.raceId} value={race.raceId}>{race.roundName} · Cuộc đua #{race.raceNumber}</option>)}</select><FiChevronDown /></div></label></div>{selected && <div className={styles.selected}><strong>{selected.roundName} · Cuộc đua #{selected.raceNumber}</strong><span>{dateTime(selected.scheduledTime)}</span><span>{selected.entryCount} ngựa đăng ký</span>{tournament?.venueName && <span><FiMapPin /> {tournament.venueName}{tournament.venueCity ? ` · ${tournament.venueCity}` : ''}</span>}<button onClick={() => setDetail(selected)}><FiEye /> Xem chi tiết</button></div>}</section>
    <section className={styles.card}><div className={styles.titleRow}><h2>Cuộc đua chưa chính thức</h2><span>{races.length}</span></div>{loading ? <p className={styles.empty}>Đang tải danh sách cuộc đua…</p> : races.length === 0 ? <p className={styles.empty}>Không có cuộc đua chưa chính thức trong giải đấu này.</p> : <div className={styles.tableWrap}><table><thead><tr><th>Cuộc đua</th><th>Vòng đấu</th><th>Thời gian</th><th>Địa điểm</th><th>Số ngựa</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{races.map((race) => <tr key={race.raceId}><td><strong>Cuộc đua #{race.raceNumber}</strong></td><td>{race.roundName}</td><td>{dateTime(race.scheduledTime)}</td><td>{race.venueName ?? tournament?.venueName ?? '—'}{(race.venueCity ?? tournament?.venueCity) && <small>{race.venueCity ?? tournament?.venueCity}</small>}</td><td>{race.entryCount}</td><td><span className={styles.status}>Chưa chính thức</span></td><td><button className={styles.view} onClick={() => setDetail(race)}><FiEye /> Xem</button></td></tr>)}</tbody></table></div>}</section>
    {detail && <div className={styles.modalLayer}><div className={styles.modal}><h2>Cuộc đua #{detail.raceNumber}</h2><dl><dt>Vòng đấu</dt><dd>{detail.roundName}</dd><dt>Thời gian</dt><dd>{dateTime(detail.scheduledTime)}</dd><dt>Số ngựa</dt><dd>{detail.entryCount}</dd><dt>Trạng thái</dt><dd>Chưa chính thức</dd></dl><p className={styles.muted}>Chỉ chuyển trạng thái sau khi kết quả, chi thưởng và các điều kiện nghiệp vụ đã sẵn sàng.</p><div><button onClick={() => setDetail(null)}>Đóng</button><button className={styles.official} disabled={!detail.canDeclareOfficial || declaring} onClick={() => void declareOfficial(detail)}><FiCheckCircle /> {declaring ? 'Đang xử lý…' : 'Chuyển chính thức'}</button></div>{!detail.canDeclareOfficial && <small className={styles.hint}>Cuộc đua chưa đáp ứng đủ điều kiện để chuyển sang chính thức.</small>}</div></div>}
  </div>;
};
export default RaceList;
